### ISSUE TITLE
Stars become black and obscure other stars when zooming out

### ISSUE THREAD

**Issue by Pandicon** [Wojtic/SkyDrawing#3]
I am not sure how you take care of not rendering faint stars on large FOVs, but the current implementation creates black dots out of them. Obviously stars will overlap on large FOVs, but currently these black dots pass in front of larger stars... But somehow the black dot then disappears again?

Can only be seen on bright (= large enough on screen) enough stars, being most visible in the case of Sirius.

It really does seem to be an issue with the stars going over each other as can be seen in the "covering-by-rotation" recording - rotating the sky projects it differently and the stars do not overlap anymore. At the same time the black spots disappear.

(The videos have to be viewed in fullscreen mode to see the issue relatively well)

https://github.com/user-attachments/assets/42ebb7b8-15a1-42db-9ef4-d6aa60ff378a

https://github.com/user-attachments/assets/b0acc4a5-6a19-4134-8ac6-9e83c07560cf

**Comment by Wojtic** [comment]
This has been solved by drawing the darker stars (when they reach minimum radius their brightness starts to decrease down to some limit) first :).
